# An example angstrom node config for sepolia

# sepolia testnet address 
angstrom_address="0x9D0ce8B3DF426008c4a4E74E7845B1bffF346a90"
# sepolia testnet address
periphery_address="0x4De4326613020a00F5545074bC578C87761295c7"
# sepolia testnet address
pool_manager_address="0xE03A1074c86CFeDd5C142C4F04F1a1536e203543"
# the tokenized gas token of the given chain
gas_token_address = "0xfff9976782d46cc05630d1f6ebab18b2324d6b14"
# sepolia deploy block
angstrom_deploy_block=7838402
