[package]
name = "sepolia-bundle-lander"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
alloy.workspace = true
alloy-chains.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
uniswap_v3_math.workspace = true
reth.workspace = true
reth-cli-util.workspace = true
reth-metrics.workspace = true
reth-network.workspace = true
reth-network-peers.workspace = true
reth-node-builder.workspace = true
reth-node-ethereum.workspace = true
reth-provider.workspace = true
angstrom-eth.workspace = true
angstrom-metrics.workspace = true
angstrom-network.workspace = true
angstrom-rpc.workspace = true
angstrom-types.workspace = true
consensus.workspace = true
matching-engine.workspace = true
order-pool.workspace = true
uniswap-v4.workspace = true
validation.workspace = true
testing-tools = { workspace = true }
clap.workspace = true
eyre.workspace = true
futures.workspace = true
itertools.workspace = true
jsonrpsee.workspace = true
rand.workspace = true
rayon = "1"
revm-interpreter.workspace = true
secp256k1 = { workspace = true, features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[target.'cfg(unix)'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]

[[bin]]
name = "bundle-lander"
path = "src/main.rs"
